### ISSUE TITLE
Using it half screen ?

### ISSUE THREAD

**Issue by Phyks** [jbt/markdown-editor#5]
Hi,

I really like this markdown editor ! But, there's a bug that would make it really better if corrected :)

I often edit files side by side on my screen (so, half the screen for one app and the other app for the other). But, if I use markdown editor on a half screen, I just get the result visualisation (_ie_ the "textarea" editor disappears).

This is not very practical, because it makes it completely impossible to use on a half screen...

**Comment by Vdragon** [comment]
:+1: for this issue

**Comment by michaelboke** [comment]
Noticed this too,
Seems to be a css media query who hides it at a certain width, comment or remove from index.html:129

``` css
@media screen and (max-width: 1024px) {
      #in {
        display: none;
      }
      #out {
        left: 0;
        padding-left: 10px;
      }
    }
```

and you can use it halfscreen
